import * as fs from "node:fs";
import { type NextRequest, NextResponse } from "next/server";
import { sql } from "@/lib/db";

export const runtime = "nodejs";

/**
 * GET /api/reports/download/:id
 *
 * Serves a report file generated by the AI assistant's generate_report
 * tool (src/lib/ai/claude/reports.ts). Authenticated the same way every
 * other /api/* route is — not in proxy.ts's publicPaths, so it inherits
 * the existing session check. No separate auth system.
 */
export async function GET(
	_req: NextRequest,
	{ params }: { params: Promise<{ id: string }> },
) {
	const { id } = await params;
	if (!/^[0-9a-f-]{36}$/i.test(id)) {
		return NextResponse.json({ error: "Invalid report id." }, { status: 400 });
	}

	const [row] = await sql`
		SELECT filename, mime_type, file_path
		FROM ai_generated_reports
		WHERE id = ${id}
	`;
	if (!row) {
		return NextResponse.json({ error: "Report not found." }, { status: 404 });
	}

	let content: Buffer;
	try {
		content = fs.readFileSync(row.file_path);
	} catch {
		return NextResponse.json(
			{ error: "Report file is no longer available." },
			{ status: 410 },
		);
	}

	return new NextResponse(new Uint8Array(content), {
		status: 200,
		headers: {
			"Content-Type": row.mime_type,
			"Content-Disposition": `attachment; filename="${row.filename}"`,
			"Content-Length": String(content.length),
		},
	});
}
